// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhYi5uXCgSeLjD98TMTdmfjcsL7YoGo5A',
    appId: '1:178525163104:web:2297ec27f5fe989158bd05',
    messagingSenderId: '178525163104',
    projectId: 'cards-b7d21',
    authDomain: 'cards-b7d21.firebaseapp.com',
    storageBucket: 'cards-b7d21.appspot.com',
    measurementId: 'G-M79W0FCPFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvSa1X5UWY225CqllTOlwWQJqNW5Ku12c',
    appId: '1:178525163104:android:b3ad24a44210ca8f58bd05',
    messagingSenderId: '178525163104',
    projectId: 'cards-b7d21',
    storageBucket: 'cards-b7d21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr8uF1SGhGjYys9Cl3DvIO54Jj5h8X-4I',
    appId: '1:178525163104:ios:4eb6eb7c2cec858658bd05',
    messagingSenderId: '178525163104',
    projectId: 'cards-b7d21',
    storageBucket: 'cards-b7d21.appspot.com',
    iosBundleId: 'com.example.cards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr8uF1SGhGjYys9Cl3DvIO54Jj5h8X-4I',
    appId: '1:178525163104:ios:0143cf77e19a048d58bd05',
    messagingSenderId: '178525163104',
    projectId: 'cards-b7d21',
    storageBucket: 'cards-b7d21.appspot.com',
    iosBundleId: 'com.example.cards.RunnerTests',
  );
}
